version: '3'
services:

  postgres:
    build: ./rpsql
    restart: always
    image: rconnect-postgres
    container_name: rpsql
    hostname: rpsql
    ports:
      - "5432:5432"     # Postgres
    networks:
      rconnect-work:
        name: rconnect-work
    volumes:
      - rconnect_pgdata:/opt/pg-data

  rstudio:
    build: ./rconnect
    restart: always
    image: rconnect-rstudio
    container_name: rconnect
    hostname: rconnect
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
#      - "4040:4040"     # Spark Web UI
#      - "4041:4041"
    networks:
      rconnect-work:
        name: rconnect-work
    volumes:
      - rconnect_rstudio:/home/rstudio
#    depends_on:
#      - hadoop
#      - hive

volumes:
  rconnect_rstudio:
  rconnect_pgdata:

networks:
  rconnect-network:
    name: rconnect-work