version: '3.5'
services:

  postgres:
    build: ./rpsql
    restart: always
    image: rconnect-postgres
    container_name: rpsql
    hostname: rpsql
    ports:
      - "5432:5432"     # Postgres
    networks:
      rconnect_network:
    volumes:
      - rconnect_pgdata:/opt/pg-data


  hive:
    build: ./rhive
    restart: always
    image: rhadoop-hive
    container_name: rhive
    hostname: rhive
    ports:
      - "10000:10000"
      - "9999:9999"  ##Hive UI
      - "9083:9083"  ## Hive Metastore
    networks:
      rconnect_network:
    depends_on:
      - postgres

  rstudio:
    build: ./rconnect
    restart: always
    image: rconnect-rstudio
    container_name: rconnect
    hostname: rconnect
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
#      - "4040:4040"     # Spark Web UI
#      - "4041:4041"
    networks:
      rconnect_network:
    volumes:
      - rconnect_rstudio:/home/rstudio
#    depends_on:
#      - hadoop
#      - hive

volumes:
  rconnect_rstudio:
  rconnect_pgdata:

networks:
  rconnect_network:
    name: rconnect
    driver: bridge